# Configuration for Alacritty, the GPU-enhanced terminal emulator

[window]
dimensions = { columns = 100, lines = 30 }
opacity = 0.95

[font]
normal = { family = "FiraMono Nerd Font Mono", style = "Bold" }
size = 9.5

[colors.primary]
background = "0x282c34"
foreground = "0xf8f8f2"

[colors.normal]
black = "0x282c34"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xe5c07b"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xabb2bf"

[colors.bright]
black = "0x5c6370"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xe5c07b"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xffffff"

[cursor]
style = { shape = "Block" }  # Choices: ▇ Block, _ Underline, | Beam

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[shell]
program = "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
args = ["-NoLogo"]
